### ISSUE TITLE
Broadcast<KDTree<GeoPoint>>problem

### ISSUE THREAD

**Issue by beidou2hao** [williamlucia/spark-dbscan#5]
in SparkDBSCAN.java, you use Broadcast<KDTree<GeoPoint>> to broadcast the KDTree to each worke node, but the broadcast variable  could to be read only, so the result of dbscan is the  local result，not the global, this kind of situation also occurs in the cluster ID value(Broadcast<AtomicLong> bgen), this will cause the error of the final result. How do you think out that problem? thank you very much!

**Comment by williamlucia** [comment]
Hi @beidou2hao.

Yes you are right.
The broadcasting of the tree should be done only after the tree is fully populated.
So instead of doing:


        KDTree<GeoPoint> pkdt = new KDTree<>(2);
        Broadcast<KDTree<GeoPoint>> bpkdt = sc.broadcast(pkdt);
        // generating single points
        JavaRDD<Tuple2<Object, GeoPoint>> points = rows.map(r -> {
            String[] fields = r.split(",");
            GeoPoint sb = new GeoPoint();
            sb.setId(Long.parseLong(fields[0]));
            sb.setLat(Double.parseDouble(fields[1]));
            sb.setLng(Double.parseDouble(fields[2]));
            addPointToKdTree(sb, bpkdt.getValue());
            return new Tuple2(sb.getId(), sb);
        });

We should write:

 KDTree<GeoPoint> pkdt = new KDTree<>(2);

        // generating single points
        rows.map(r -> {
            String[] fields = r.split(",");
            GeoPoint sb = new GeoPoint();
            sb.setId(Long.parseLong(fields[0]));
            sb.setLat(Double.parseDouble(fields[1]));
            sb.setLng(Double.parseDouble(fields[2]));
            return new Tuple2(sb.getId(), sb);
        }).collect()
          .stream()
          .forEach(geoPoint -> addPointToKdTree(sb, bpkdt.getValue());)

  Broadcast<KDTree<GeoPoint>> bpkdt = sc.broadcast(pkdt);

in this way we will broadcast to all the nodes the tree with  all the data points.
I will fix it soon.
Thanks.

**Comment by williamlucia** [comment]
The assumption here is that we are able to build and to broadcast the tree from the master. If this is not the case, we have to change the code in order that each executor will be able to access to the list of points and to create a local KD-Tree since a executor's ram is typically >> master's memory

**Comment by beidou2hao** [comment]
Thank you very much for you reply! At the end of this algorithm, the output of the clustering Id ("## Broadcast<AtomicLong> bgen = jsc.broadcast(idGen)") also has the same problem
